#+TITLE: Building this site

The site is statically generated from orgmode-files using emacs, and then hosted on github pages.
The source is on [[https://github.com/ochsnerd/thoughts][github]].

1. As part of a github action:
   1. nix installs emacs with its required packages (based on using [[https://nix.dev/manual/nix/2.22/command-ref/new-cli/nix3-shell][nix shell]] as a shebang).
   2. ox-publish generates html from org-files in ~content/~.

      I use a pre-generated [[https://github.com/gongzhitaao/orgcss/tree/master][stylesheet for org-exports]], which in includes syntax-highlighting for src-blocks.
      For now this seems (almost) good enough, but its missing highlighting for nix and haskell.
      There is a way to make htmlize generate css when exporting the org-files, but for that to work a grammar
      for every language needs to be available, /and/ it should not clash with a global css.
   3. the generated files are pushed to the ~ochsnerd/ochsnerd.github.io~ repo.
2. github magically publishes the files.

The above process is largely based on the tutorial by [[https://systemcrafters.net/publishing-websites-with-org-mode/building-the-site/][System Crafters]].
