name: Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Prepare environment
        run: |
          rm -r public || true
          mkdir public

      - name: Build
        run: ./build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: public
     	  path: public/
          retention-days: 5
